root_dir: '/home/chrstphr/projects/ecGAN/result'

device: 'cpu'
device_id: 'auto'

batch_size: 32
nepochs: 10
start_epoch: 0
save_freq: 5

data:
  func: 'get_mnist'
  args: []
  kwargs: {'train':True}

model: 'Classifier'
nets:
  # generator:
  #   type: 'GenFC'
  #   param: '${root_dir}/params/${model}.${nets.generator.type}.${start_epoch}.params'
  #   save: '${root_dir}/params/${model}.${nets.generator.type}.${epoch}.params'
  # discriminator:
  #   type: 'DiscrFC'
  #   param: '${root_dir}/params/${model}.${nets.discriminator.type}.${start_epoch}.params'
  #   save: '${root_dir}/params/${model}.${nets.discriminator.type}.${epoch}.params'
  classifier:
    type: 'ClassFC'
    param: '${root_dir}/params/${model}.${nets.classifier.type}.${start_epoch}.params'
    save: '${root_dir}/params/${model}.${nets.classifier.type}.${epoch}.params'

log: '${root_dir}/log/${model}.log'
