device: 'cpu'
device_id: 0

batch_size: 32
nepochs: 10

data_func: 'get_mnist_single'
data_args: []
data_kwargs: {'train':True,'label':5}

netG: 'GenFC'
paramG: /home/chrstphr/projects/ecGAN/result/G.params
saveG: NULL
netD: 'DiscrFC'
paramD: /home/chrstphr/projects/ecGAN/result/D.params
saveD: NULL

log: '/home/chrstphr/projects/ecGAN/result/test.log'
genout: '/home/chrstphr/projects/ecGAN/result/testgen.pdf'
