root_dir: '/home/chrstphr/projects/ecGAN/result'

device: 'cpu'
device_id: 0

batch_size: 32
nepochs: 10
start_epoch: 10
save_freq: 0

data_func: 'get_mnist_single'
data_args: []
data_kwargs: {'train':True,'label':5}

netG: 'GenFC'
paramG: '${root_dir}/G.${start_epoch}.params'
saveG: NULL
netD: 'DiscrFC'
paramD: '${root_dir}/D.${start_epoch}.params'
saveD: NULL

log: '${root_dir}/test.log'
genout: '${root_dir}/testgen.${start_epoch}.png'
