root_dir: '/home/chrstphr/projects/ecGAN/result'

device: 'cpu'
device_id: 0

batch_size: 32
nepochs: 10
start_epoch: 0
save_freq: 5

data_func: 'get_mnist'
data_args: []
data_kwargs: {'train':True}

model: 'CGAN'
netG: 'GenFC'
paramG: NULL
saveG: '${root_dir}/params/${model}.${netG}.${epoch}.params'
netD: 'DiscrFC'
paramD: NULL
saveD: '${root_dir}/params/${model}.${netD}.${epoch}.params'

log: '${root_dir}/log/${model}.log'
genout: '${root_dir}/gen/${model}.${netG}.${start_epoch}.png'
