root_dir: '/home/chrstphr/projects/ecGAN/result'

device: 'cpu'
device_id: 0

batch_size: 32
nepochs: 10
start_epoch: 0
save_freq: 0

data_func: 'get_mnist_single'
data_args: []
data_kwargs: {'train':True,'label':5}

netG: 'GenFC'
paramG: NULL
saveG: '${root_dir}/${netG}.${epoch}.params'
netD: 'DiscrFC'
paramD: NULL
saveD: '${root_dir}/${netD}.${epoch}.params'

log: '${root_dir}/logfile.log'
genout: '${root_dir}/gen.${netG}.${start_epoch}.png'
