root_dir: '/home/chrstphr/projects/ecGAN/result'
exp_dir: 'mnist_full'

device: 'cpu'
device_id: 'auto'
debug: False

batch_size: 64
nepochs: 10
start_epoch: 0
save_freq: 5

init: False

data:
  func: 'get_mnist'
  args: []
  kwargs: {'train':True,'ret_label':False}
  bbox: [-1,1]

model: 'WGAN'
nets:
  generator:
    type: 'GSFC'
    kwargs: {}
    param: '${root_dir}/${exp_dir}/params/${model}.${nets.generator.type}.${start_epoch}.params'
    save: '${root_dir}/${exp_dir}/params/${model}.${nets.generator.type}.${epoch}.params'
  discriminator:
    type: 'DSFC'
    kwargs: {'outnum': 1}
    param: '${root_dir}/${exp_dir}/params/${model}.${nets.discriminator.type}.${start_epoch}.params'
    save: '${root_dir}/${exp_dir}/params/${model}.${nets.discriminator.type}.${epoch}.params'
  # classifier:
  #   type: 'ClassFC'
  #   param: '${root_dir}/params/${model}.${nets.classifier.type}.${start_epoch}.params'
  #   save: '${root_dir}/params/${model}.${nets.classifier.type}.${epoch}.params'

log: '${root_dir}/${exp_dir}/log/${model}.log'
gen_freq: 5
genout: '${root_dir}/${exp_dir}/gen/${model}.${nets.generator.type}.${epoch}.png'
ncritic: 5
